// AUTO-GENERATED by server/tools/apigen from internal/model/dto/response.
// DO NOT EDIT. Run `pnpm gen:api` to regenerate.
declare namespace Api {
    interface IDResp {
      id: string
    }
  namespace Auth {
    interface LoginResp {
      accessToken: string
      refreshToken: string
      expiresIn: number
    }

    interface RefreshTokenResp {
      accessToken: string
      refreshToken: string
      expiresIn: number
    }

    interface AvatarUploadResp {
      avatar: string
    }

    interface UserInfoResp {
      id: string
      username: string
      realName: string
      nickname: string
      gender: string
      avatar: string
      email: string
      phone: string
      dataScope: number
      deptId: string
      roles: string[]
      permissions: string[]
      mustChangePassword: boolean
    }

    interface RoleBriefResp {
      code: string
      name: string
    }

    interface LoginStatsResp {
      totalLogins: number
      logins30d: number
      failed30d: number
    }

    interface DailyActivityResp {
      date: string
      success: number
      failed: number
    }

    interface RecentLoginResp {
      time: string
      ip: string
      browser: string
      os: string
      code: number
      msg: string
    }

    interface UserOverviewResp {
      id: string
      username: string
      realName: string
      avatar: string
      email: string
      phone: string
      deptName: string
      roles: Api.Auth.RoleBriefResp[]
      createdAt: string
      lastLoginTime: string | null
      lastLoginIp: string
      stats: Api.Auth.LoginStatsResp
      dailyActivity: Api.Auth.DailyActivityResp[]
      recentLogins: Api.Auth.RecentLoginResp[]
    }

    interface VerifyPasswordResp {
      valid: boolean
    }
  }

  namespace Dict {
    interface DictItem {
      label: string
      value: string
      list_class: string
      is_default: boolean
      sort: number
    }

    interface DictDataResp {
      id: string
      typeId: string
      listClass: string
      label: string
      value: string
      isDefault: number
      sort: number
      status: number
      remark: string
      createdAt: string
      updatedAt: string
    }

    interface DictTypeResp {
      id: string
      code: string
      name: string
      status: number
      remark: string
      createdAt: string
      updatedAt: string
    }
  }

  namespace System {
    interface DeptResp {
      id: string
      parentId: string
      ancestors: string
      name: string
      sort: number
      leader: string
      phone: string
      email: string
      status: number
      children?: Api.System.DeptResp[]
      createdAt: string
    }

    interface MenuResp {
      id: string
      parentId: string
      name: string
      type: string
      perms: string
      path: string
      component: string
      icon: string
      sort: number
      visible: number
      status: number
      children?: Api.System.MenuResp[]
      createdAt: string
    }

    interface RoleResp {
      id: string
      name: string
      code: string
      dataScope: number
      sort: number
      status: number
      remark: string
      menuIds: string[]
      deptIds: string[]
      createdAt: string
    }

    interface RoleOptionResp {
      id: string
      name: string
      code: string
      sort: number
      status: number
    }

    interface UserResp {
      id: string
      username: string
      realName: string
      nickname: string
      gender: string
      email: string
      phone: string
      avatar: string
      deptId: string
      deptName: string
      status: number
      remark: string
      lastLoginTime: string | null
      createdAt: string
      roleNames: string[]
      roleIds: string[]
    }
  }

  namespace Notice {
    interface NoticeResp {
      id: string
      title: string
      content: string
      noticeType: number
      status: number
      priority: number
      publishType: number
      targetType: number
      targetIds: string
      targetDesc: string
      readStatus?: number | null
      createBy: string
      publishTime: string | null
      createdAt: string
      updatedAt: string
    }

    interface NoticeReadUserResp {
      userId: string
      username: string
      realName: string
      deptName: string
      phone: string
      readTime: string | null
    }

    interface NoticeTargetUserResp {
      id: string
      username: string
      realName: string
    }

    interface NoticeMyItemResp {
      id: string
      title: string
      content: string
      noticeType: number
      priority: number
      isRead: boolean
      publishTime: string | null
    }

    interface NoticeMyListResp {
      list: Api.Notice.NoticeMyItemResp[]
      unreadCount: number
    }
  }

  namespace Config {
    interface ConfigResp {
      id: string
      name: string
      configKey: string
      configValue: string
      configType: string
      remark: string
      status: number
      createdAt: string
      updatedAt: string
    }
  }

  namespace Job {
    interface JobResp {
      id: string
      name: string
      jobGroup: string
      cronExpression: string
      invokeTarget: string
      invokeParams: string
      concurrent: number
      retryCount: number
      retryInterval: number
      status: number
      runAtStartup: number
      remark: string
      nextRunTime: string | null
      createdAt: string
      updatedAt: string
    }

    interface JobLogResp {
      id: string
      jobId: string
      jobName: string
      jobGroup: string
      invokeTarget: string
      triggerType: number
      startTime: string
      endTime: string | null
      costTime: number
      status: number
      errorMsg: string
    }

    interface JobTargetResp {
      target: string
      displayName: string
      hasParams: boolean
      paramSchema?: Record<string, unknown>
    }

    interface JobHealthResp {
      schedulerRunning: boolean
      instanceId: string
      totalJobs: number
      runningJobs: number
      uptime: string
    }
  }

  namespace Log {
    interface LoginLogResp {
      id: string
      userId: string
      username: string
      ip: string
      location: string
      browser: string
      os: string
      code: number
      msg: string
      loginTime: string
    }

    interface OperationLogResp {
      id: string
      userId: string
      username: string
      module: string
      operationType: string
      requestMethod: string
      requestUrl: string
      requestParams: string
      responseResult: string
      costTime: number
      ip: string
      code: number
      errorMsg: string
      operTime: string
    }
  }

  namespace Monitor {
    interface CacheKeyInfo {
      key: string
      type: string
    }

    interface ListKeysResponse {
      keys: Api.Monitor.CacheKeyInfo[]
      cursor: string
    }

    interface DeleteKeysResponse {
      deleted: number
    }

    interface CacheValuePage {
      key: string
      type: string
      ttl: number
      total: number
      start: number
      has_more: boolean
      next_cursor: string
      truncated: boolean
      value: unknown
    }

    interface OnlineSession {
      userId: string
      username: string
      realName: string
      deptName: string
      ip: string
      browser: string
      os: string
      loginAt: string
      expireAt: string
      tokenCount: number
    }

    interface PprofProfileEntry {
      name: string
      description: string
      category: string
      unit: string
      count: number
    }

    interface PprofStatusResponse {
      enabled: boolean
      autoOffSeconds: number
      remainingSeconds: number
      profiles: Api.Monitor.PprofProfileEntry[]
    }

    interface FlameNode {
      name: string
      value: number
      children?: (Api.Monitor.FlameNode | null)[]
    }

    interface PprofTopFunc {
      fn: string
      name: string
      file: string
      line: number
      flat: number
      cum: number
    }

    interface PprofProfileResponse {
      name: string
      unit: string
      sampleType: string
      sampleCount: number
      totalValue: number
      truncated: boolean
      flame: Api.Monitor.FlameNode | null
      top: Api.Monitor.PprofTopFunc[]
    }

    interface ServerMonitorResp {
      server: Api.Monitor.ServerInfo
      host: Api.Monitor.HostInfo
      cpu: Api.Monitor.CPUInfo
      memory: Api.Monitor.MemoryInfo
      goroutines: Api.Monitor.GoroutineInfo
      gc: Api.Monitor.GCInfo
      disk: Api.Monitor.DiskInfo
    }

    interface ServerInfo {
      version: string
      buildTime: string
      commitHash: string
      startTime: string
      uptime: string
      uptimeSeconds: number
      error?: string
    }

    interface HostInfo {
      hostname: string
      os: string
      platform: string
      platformVersion: string
      kernelVersion: string
      kernelArch: string
      goVersion: string
      arch: string
      pid: number
      bootTime: string
      uptimeSeconds: number
      error?: string
    }

    interface CPUInfo {
      numCPU: number
      usagePercent: number | null
      perCore?: number[]
      load?: Api.Monitor.LoadInfo | null
      error?: string
    }

    interface LoadInfo {
      load1: number | null
      load5: number | null
      load15: number | null
      error?: string
    }

    interface MemoryInfo {
      allocMB: number
      totalAllocMB: number
      sysMB: number
      heapAllocMB: number
      heapSysMB: number
      system?: Api.Monitor.SystemMemoryInfo | null
      swap?: Api.Monitor.SwapMemoryInfo | null
      error?: string
    }

    interface SystemMemoryInfo {
      totalMB: number
      usedMB: number
      availableMB: number
      usedPercent: number
    }

    interface SwapMemoryInfo {
      totalMB: number
      usedMB: number
      freeMB: number
      usedPercent: number
    }

    interface GoroutineInfo {
      count: number
      error?: string
    }

    interface GCInfo {
      numGC: number
      pauseTotalMs: number | null
      lastPauseMs: number | null
      error?: string
    }

    interface DiskInfo {
      path: string
      totalGB: number
      usedGB: number
      freeGB: number
      usagePercent: number
      error?: string
    }

    interface ServerHistoryPoint {
      timestamp: string
      cpu?: number | null
      memSys?: number | null
      heapAlloc?: number | null
      sysMem?: number | null
      goroutines?: number | null
      gcNum?: number | null
      gcPauseMs?: number | null
      disk?: number | null
      load1?: number | null
      uptime?: number | null
    }

    interface ServerHistorySnapshot {
      window_seconds: number
      step_seconds: number
      buckets: Api.Monitor.ServerHistoryPoint[]
    }

    interface SQLHistoryPoint {
      timestamp: string
      count: number
      qps: number
      avg_ms: number
      p50_ms: number
      p95_ms: number
      p99_ms: number
      max_ms: number
      error_count: number
      slow_count: number
    }

    interface SQLHistorySnapshot {
      window_seconds: number
      step_seconds: number
      slow_threshold_ms: number
      recent_qps: number
      buckets: Api.Monitor.SQLHistoryPoint[]
    }

    interface SQLGlobalStats {
      count: number
      avg_ms: number
      max_ms: number
      min_ms: number
      p50_ms: number
      p95_ms: number
      p99_ms: number
      error_count: number
      slow_count: number
      slow_threshold_ms: number
    }

    interface SQLDimStats {
      count: number
      avg_ms: number
      max_ms: number
      min_ms: number
      p50_ms?: number
      p95_ms?: number
      p99_ms?: number
    }

    interface SQLQueryEntry {
      timestamp: string
      duration_ms: number
      sql: string
      table: string
      operation: string
      is_error: boolean
      is_slow: boolean
    }

    interface SQLStatsSnapshot {
      global: Api.Monitor.SQLGlobalStats
      by_table: Record<string, Api.Monitor.SQLDimStats>
      by_operation: Record<string, Api.Monitor.SQLDimStats>
      slow_queries: Api.Monitor.SQLQueryEntry[]
    }
  }

  namespace File {
    interface FileResp {
      id: string
      name: string
      originalName: string
      size: number
      mimeType: string
      ext: string
      category: string
      storageType: string
      createdBy?: string
      createdAt: string
      updatedAt: string
    }

    interface FileStatsResp {
      total: number
      totalSize: number
      weekUploads: number
      categoryCounts: Record<string, number>
    }

    interface UploadFilesResp {
      items: Api.File.FileResp[]
    }
  }
}
