package repository

import (
	"context"

	"github.com/tangwy-t/webmanager-server/internal/model/dto/request"
	"github.com/tangwy-t/webmanager-server/internal/model/entity"

	"gorm.io/gorm"
)

type RoleRepo struct {
	db *gorm.DB
}

// NewRoleRepository returns a RoleRepository backed by the given *gorm.DB.
// Snowflake IDs for association records (SysRoleMenu, SysRoleDept) are
// generated by the GORM BeforeCreate callback (database.RegisterIDCallback).
func NewRoleRepository(db *gorm.DB) *RoleRepo {
	return &RoleRepo{db: db}
}

func (r *RoleRepo) applyRoleFilters(db *gorm.DB, query *request.RoleQuery) *gorm.DB {
	if query.Name != "" {
		db = db.Where("name LIKE ?", "%"+query.Name+"%")
	}
	if query.Code != "" {
		db = db.Where("code LIKE ?", "%"+query.Code+"%")
	}
	if query.Status != nil {
		db = db.Where("status = ?", *query.Status)
	}
	return db
}

func (r *RoleRepo) FindPage(ctx context.Context, query *request.RoleQuery) ([]entity.SysRole, int64, error) {
	var total int64
	countDB := r.applyRoleFilters(r.db.WithContext(ctx).Model(&entity.SysRole{}), query)
	if err := countDB.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	dataDB := r.applyRoleFilters(r.db.WithContext(ctx).Model(&entity.SysRole{}), query)
	var roles []entity.SysRole
	err := dataDB.Offset(query.Offset()).Limit(query.GetPageSize()).Order("sort ASC, id ASC").Find(&roles).Error
	return roles, total, err
}

func (r *RoleRepo) FindAll(ctx context.Context) ([]entity.SysRole, error) {
	var roles []entity.SysRole
	err := r.db.WithContext(ctx).Order("sort ASC, id ASC").Find(&roles).Error
	return roles, err
}

func (r *RoleRepo) FindByID(ctx context.Context, id uint64) (*entity.SysRole, error) {
	var role entity.SysRole
	err := r.db.WithContext(ctx).Preload("Menus").Preload("Depts").First(&role, id).Error
	if err != nil {
		return nil, err
	}
	return &role, nil
}

func (r *RoleRepo) CreateWithAssociations(ctx context.Context, role *entity.SysRole, menuIDs, deptIDs []uint64) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := tx.Create(role).Error; err != nil {
			return err
		}
		if err := r.replaceRoleMenus(tx, role.ID, menuIDs); err != nil {
			return err
		}
		if err := r.replaceRoleDepts(tx, role.ID, deptIDs); err != nil {
			return err
		}
		return nil
	})
}

// UpdateWithAssociationsAndUserIDs updates the role and its associations
// and returns the IDs of users currently assigned to the role, all within a single
// transaction. This eliminates the race window between querying user IDs and committing
// the update — the caller can invalidate the permission cache for every user that was
// assigned at the moment the transaction ran.
func (r *RoleRepo) UpdateWithAssociationsAndUserIDs(ctx context.Context, role *entity.SysRole, menuIDs, deptIDs []uint64) ([]uint64, error) {
	var userIDs []uint64
	err := r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := tx.WithContext(ctx).Table("sys_user_role").
			Where("role_id = ?", role.ID).
			Pluck("user_id", &userIDs).Error; err != nil {
			return err
		}
		return r.updateWithAssociationsInTx(ctx, tx, role, menuIDs, deptIDs)
	})
	return userIDs, err
}

func (r *RoleRepo) updateWithAssociationsInTx(ctx context.Context, tx *gorm.DB, role *entity.SysRole, menuIDs, deptIDs []uint64) error {
	if err := tx.WithContext(ctx).Model(role).Updates(role).Error; err != nil {
		return err
	}
	if err := r.replaceRoleMenus(tx, role.ID, menuIDs); err != nil {
		return err
	}
	if err := r.replaceRoleDepts(tx, role.ID, deptIDs); err != nil {
		return err
	}
	return nil
}

func (r *RoleRepo) replaceRoleMenus(tx *gorm.DB, roleID uint64, menuIDs []uint64) error {
	if err := tx.Where("role_id = ?", roleID).Delete(&entity.SysRoleMenu{}).Error; err != nil {
		return err
	}
	if len(menuIDs) == 0 {
		return nil
	}
	roleMenus := make([]entity.SysRoleMenu, len(menuIDs))
	for i, menuID := range menuIDs {
		roleMenus[i] = entity.SysRoleMenu{
			RoleID: roleID,
			MenuID: menuID,
		}
	}
	return tx.Create(&roleMenus).Error
}

func (r *RoleRepo) replaceRoleDepts(tx *gorm.DB, roleID uint64, deptIDs []uint64) error {
	if err := tx.Where("role_id = ?", roleID).Delete(&entity.SysRoleDept{}).Error; err != nil {
		return err
	}
	if len(deptIDs) == 0 {
		return nil
	}
	roleDepts := make([]entity.SysRoleDept, len(deptIDs))
	for i, deptID := range deptIDs {
		roleDepts[i] = entity.SysRoleDept{
			RoleID: roleID,
			DeptID: deptID,
		}
	}
	return tx.Create(&roleDepts).Error
}

func (r *RoleRepo) Delete(ctx context.Context, id uint64) error {
	return r.db.WithContext(ctx).Delete(&entity.SysRole{}, id).Error
}

// UpdateStatus updates only the status column — role status changes must go
// through the guarded service path (admin role is not toggleable).
func (r *RoleRepo) UpdateStatus(ctx context.Context, id uint64, status int8) error {
	return r.db.WithContext(ctx).Model(&entity.SysRole{}).Where("id = ?", id).
		Update("status", status).Error
}

// UpdateSort updates only the sort column. Unlike the full Update path
// (UpdateWithAssociationsAndUserIDs) it never touches menu/dept associations,
// so batch reordering from the list page is cheap and side-effect free.
func (r *RoleRepo) UpdateSort(ctx context.Context, id uint64, sort int) error {
	return r.db.WithContext(ctx).Model(&entity.SysRole{}).Where("id = ?", id).
		Update("sort", sort).Error
}

func (r *RoleRepo) DeleteWithAssociations(ctx context.Context, id uint64) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := r.DeleteRoleMenusTx(ctx, tx, id); err != nil {
			return err
		}
		if err := r.DeleteRoleDeptsTx(ctx, tx, id); err != nil {
			return err
		}
		if err := r.DeleteTx(ctx, tx, id); err != nil {
			return err
		}
		return nil
	})
}

func (r *RoleRepo) DeleteTx(ctx context.Context, tx *gorm.DB, id uint64) error {
	return tx.WithContext(ctx).Delete(&entity.SysRole{}, id).Error
}

func (r *RoleRepo) DeleteRoleMenusTx(ctx context.Context, tx *gorm.DB, roleID uint64) error {
	return tx.WithContext(ctx).Where("role_id = ?", roleID).Delete(&entity.SysRoleMenu{}).Error
}

func (r *RoleRepo) DeleteRoleDeptsTx(ctx context.Context, tx *gorm.DB, roleID uint64) error {
	return tx.WithContext(ctx).Where("role_id = ?", roleID).Delete(&entity.SysRoleDept{}).Error
}

func (r *RoleRepo) FindUserIDsByRoleID(ctx context.Context, roleID uint64) ([]uint64, error) {
	var userIDs []uint64
	err := r.db.WithContext(ctx).Table("sys_user_role").
		Where("role_id = ?", roleID).
		Pluck("user_id", &userIDs).Error
	return userIDs, err
}
