package main

import (
	"os"
	"path/filepath"
	"testing"
)

// writeSample 在临时目录写入样本 Go 源文件,交给 genPackage 解析。
func writeSample(t *testing.T, dir, name, src string) string {
	t.Helper()
	p := filepath.Join(dir, name)
	if err := os.WriteFile(p, []byte(src), 0o644); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
	return p
}

func TestGenPackageSortsAndEmitsStably(t *testing.T) {
	dir := t.TempDir()
	// auth.go 声明顺序在 user.go 之前,确保"文件排序 + 声明顺序"双重稳定。
	writeSample(t, dir, "auth.go", `package response

import (
	"time"

	"github.com/tangwy-t/webmanager-server/internal/pkg/util"
)

// UserInfoResp 登录用户信息。
type UserInfoResp struct {
	ID    uint64      ` + "`json:\"id,string\"`" + `
	Name  string      ` + "`json:\"name\"`" + `
	Admin bool        ` + "`json:\"admin\"`" + `
	Seen  *time.Time  ` + "`json:\"seen,omitempty\"`" + `
	Skip  string      ` + "`json:\"-\"`" + `
}

// RoleBriefResp 角色简要信息。
type RoleBriefResp struct {
	ID   uint64 ` + "`json:\"id,string\"`" + `
	Name string ` + "`json:\"name\"`" + `
}
`)
	writeSample(t, dir, "user.go", `package response

import "github.com/tangwy-t/webmanager-server/internal/pkg/util"

// UserResp 用户详情。
type UserResp struct {
	ID        uint64             ` + "`json:\"id,string\"`" + `
	DeptID    util.JsonUint64    ` + "`json:\"deptId,string\"`" + `
	MenuIDs   util.JsonUint64Slice ` + "`json:\"menuIds\"`" + `
	RealName  *string            ` + "`json:\"realName,omitempty\"`" + `
	Created   util.JSONTime      ` + "`json:\"createdAt\"`" + `
	Counts    map[string]int64   ` + "`json:\"counts\"`" + `
	Children  []UserResp         ` + "`json:\"children,omitempty\"`" + `
	Brief     *RoleBriefResp     ` + "`json:\"brief,omitempty\"`" + `
	Any       interface{}        ` + "`json:\"any\"`" + `
}
`)

	got, err := genPackage(dir)
	if err != nil {
		t.Fatalf("genPackage: %v", err)
	}
	want := `// AUTO-GENERATED by server/tools/apigen from internal/model/dto/response.
// DO NOT EDIT. Run ` + "`pnpm gen:api`" + ` to regenerate.
declare namespace Api {
  namespace Auth {
    interface UserInfoResp {
      id: string
      name: string
      admin: boolean
      seen?: string | null
    }

    interface RoleBriefResp {
      id: string
      name: string
    }
  }

  namespace System {
    interface UserResp {
      id: string
      deptId: string
      menuIds: string[]
      realName?: string | null
      createdAt: string
      counts: Record<string, number>
      children?: Api.System.UserResp[]
      brief?: Api.Auth.RoleBriefResp | null
      any: unknown
    }
  }
}
`
	if got != want {
		t.Fatalf("genPackage output mismatch\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestGenPackageRejectsUnknownFileMapping(t *testing.T) {
	dir := t.TempDir()
	writeSample(t, dir, "mystery.go", `package response

type X struct {
	A string ` + "`json:\"a\"`" + `
}
`)
	if _, err := genPackage(dir); err == nil {
		t.Fatal("want fatal for unmapped file, got nil error")
	}
}

func TestGenPackageRejectsUnknownSelectorType(t *testing.T) {
	dir := t.TempDir()
	writeSample(t, dir, "user.go", `package response

import "otherpkg"

type Y struct {
	A otherpkg.Foreign ` + "`json:\"a\"`" + `
}
`)
	if _, err := genPackage(dir); err == nil {
		t.Fatal("want fatal for unknown selector type, got nil error")
	}
}

func TestGenPackageInlinesEmbeddedFields(t *testing.T) {
	dir := t.TempDir()
	writeSample(t, dir, "dept.go", `package response

// Base 基础字段。
type Base struct {
	ID   uint64 ` + "`json:\"id,string\"`" + `
	Name string ` + "`json:\"name\"`" + `
}

// DeptResp 部门详情(内嵌 Base)。
type DeptResp struct {
	Base
	Parent uint64 ` + "`json:\"parent,string\"`" + `
}
`)
	got, err := genPackage(dir)
	if err != nil {
		t.Fatalf("genPackage: %v", err)
	}
	wantDeps := `  namespace System {
    interface Base {
      id: string
      name: string
    }

    interface DeptResp {
      id: string
      name: string
      parent: string
    }
  }
`
	if !contains(got, wantDeps) {
		t.Fatalf("embedded fields not inlined\n--- got ---\n%s\n--- want ---\n%s", got, wantDeps)
	}
}

func contains(s, sub string) bool {
	return len(sub) == 0 || (len(s) >= len(sub) && indexOf(s, sub) >= 0)
}

func indexOf(s, sub string) int {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return i
		}
	}
	return -1
}