package service

import (
	"context"
	"errors"
	"strconv"
	"strings"

	"github.com/tangwy-t/webmanager-server/internal/model/dto/request"
	"github.com/tangwy-t/webmanager-server/internal/model/dto/response"
	"github.com/tangwy-t/webmanager-server/internal/model/entity"
	"github.com/tangwy-t/webmanager-server/internal/pkg/apperror"
	"github.com/tangwy-t/webmanager-server/internal/pkg/logger"
	"github.com/tangwy-t/webmanager-server/internal/pkg/util"

	"go.uber.org/zap"
	"gorm.io/gorm"
)

// DeptRepositoryInterface 由 service/interface.go 迁移至此:接口定义在消费方,
// 不再维护包级中央接口文件。
type DeptRepositoryInterface interface {
	FindAll(ctx context.Context) ([]entity.SysDept, error)
	FindByID(ctx context.Context, id uint64) (*entity.SysDept, error)
	Create(ctx context.Context, dept *entity.SysDept) error
	CreateWithAncestorsTx(ctx context.Context, dept *entity.SysDept, parentAncestors string) error
	Update(ctx context.Context, dept *entity.SysDept) error
	UpdateWithAncestorsTx(ctx context.Context, dept *entity.SysDept) error
	Delete(ctx context.Context, id uint64) error
	HasChildren(ctx context.Context, id uint64) (bool, error)
	HasUsers(ctx context.Context, id uint64) (bool, error)
	FindChildDeptIDs(ctx context.Context, deptID uint64) ([]uint64, error)
	UpdateSort(ctx context.Context, id uint64, sort int) error
}

type DeptService struct {
	repo   DeptRepositoryInterface
	logger logger.LoggerInterface
}

// NewDeptService constructs a DeptService with the given dependencies.
// Snowflake ID generation is handled by GORM callbacks (database.RegisterIDCallback).
func NewDeptService(repo DeptRepositoryInterface, logger logger.LoggerInterface) *DeptService {
	return &DeptService{repo: repo, logger: logger}
}

func (s *DeptService) FindTree(ctx context.Context, query request.DeptQuery) ([]response.DeptResp, error) {
	depts, err := s.repo.FindAll(ctx)
	if err != nil {
		return nil, err
	}
	tree := s.buildDeptTree(depts)
	// 无筛选条件时直接返回全树，行为与历史版本一致。
	if query.Name == "" && query.Status == nil {
		return tree, nil
	}
	return s.filterDeptTree(tree, query), nil
}

// filterDeptTree 对已构建的部门树按查询条件裁剪（语义对齐菜单管理）：
// 保留「自身匹配」或「存在匹配的后代」的节点，使命中子节点时其祖先链路不丢失。
func (s *DeptService) filterDeptTree(tree []response.DeptResp, query request.DeptQuery) []response.DeptResp {
	result := make([]response.DeptResp, 0, len(tree))
	for _, node := range tree {
		// 先递归处理子节点，判断该分支是否含命中节点。
		children := s.filterDeptTree(node.Children, query)
		childrenMatch := len(children) > 0
		selfMatch := s.deptMatches(node, query)

		if selfMatch {
			// 自身命中：保留完整子树（沿用原 children，不因筛选而丢子）。
			result = append(result, node)
			continue
		}
		if childrenMatch {
			node.Children = children
			result = append(result, node)
		}
	}
	return result
}

// deptMatches 判断单个节点是否命中查询条件（名称模糊、状态精确）。
func (s *DeptService) deptMatches(node response.DeptResp, query request.DeptQuery) bool {
	if query.Name != "" && !strings.Contains(strings.ToLower(node.Name), strings.ToLower(query.Name)) {
		return false
	}
	if query.Status != nil && node.Status != *query.Status {
		return false
	}
	return true
}

func (s *DeptService) FindByID(ctx context.Context, id uint64) (*response.DeptResp, error) {
	dept, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return nil, translateNotFound(err, "部门不存在")
	}
	resp := util.MapEntity[response.DeptResp](dept, s.logger)
	return &resp, nil
}

func (s *DeptService) Create(ctx context.Context, req *request.CreateDeptReq) (uint64, error) {
	// ID is auto-generated by the GORM BeforeCreate callback (database.RegisterIDCallback).
	dept := &entity.SysDept{}
	// ParentID is *util.JsonUint64 in the request to preserve snowflake-ID
	// precision; copier converts it to the entity's *uint64 automatically
	// (behavior locked by util.TestCopyEntityJsonUint64Pointer).
	util.CopyEntity(dept, req, s.logger)

	// Defaults.
	if dept.Status == nil {
		enabled := entity.DeptStatusEnabled
		dept.Status = &enabled
	}

	// Validate parent existence BEFORE the transaction (translates to 400).
	// Previously Create ran first and an invalid parent returned 400 AFTER
	// the dept had already been inserted — orphan row.
	var parentAncestors string
	if dept.ParentID != nil && *dept.ParentID != 0 {
		parent, err := s.repo.FindByID(ctx, *dept.ParentID)
		if err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				return 0, apperror.BadRequest("父部门不存在")
			}
			return 0, err
		}
		parentAncestors = parent.Ancestors
	}

	// CreateWithAncestorsTx atomizes Create + UpdateAncestors in one
	// transaction. Ancestors is a comma-separated chain of department IDs
	// from root to self (e.g. "1,3,7"); dept.ID is assigned by the GORM
	// id:generate callback during Create, so the final string can only be
	// composed inside the transaction. Without atomicity, Create could
	// succeed while UpdateAncestors fails — a dept with empty ancestors
	// breaks tree queries and dept-dimension data scope.
	if err := s.repo.CreateWithAncestorsTx(ctx, dept, parentAncestors); err != nil {
		s.logger.Warn("failed to create dept", zap.String("name", req.Name), zap.Error(err))
		return 0, err
	}
	s.logger.Info("dept created", zap.Uint64("deptId", dept.ID), zap.String("name", dept.Name))
	return dept.ID, nil
}

func (s *DeptService) Update(ctx context.Context, req *request.UpdateDeptReq) error {
	dept, err := s.repo.FindByID(ctx, req.ID)
	if err != nil {
		return translateNotFound(err, "部门不存在")
	}

	oldParentID := uint64(0)
	if dept.ParentID != nil {
		oldParentID = *dept.ParentID
	}

	// ParentID is *util.JsonUint64 in the request to preserve snowflake-ID
	// precision; copier converts it to the entity's *uint64 automatically
	// (behavior locked by util.TestCopyEntityJsonUint64Pointer).
	util.CopyEntity(dept, req, s.logger)

	// If parentID changed, validate and recalculate ancestors.
	newParentID := uint64(0)
	if dept.ParentID != nil {
		newParentID = *dept.ParentID
	}
	if newParentID != oldParentID {
		// Check circular reference: cannot move to self or descendant.
		if dept.ParentID != nil && *dept.ParentID == dept.ID {
			return apperror.BadRequest("不能将部门移动到自身下")
		}

		// Check if target parent is a descendant of the current dept.
		// Look up the target parent's ancestors and see if they contain the current dept's ID.
		if dept.ParentID != nil && *dept.ParentID != 0 {
			targetParent, err := s.repo.FindByID(ctx, *dept.ParentID)
			if err != nil {
				if errors.Is(err, gorm.ErrRecordNotFound) {
					return apperror.BadRequest("父部门不存在")
				}
				return err
			}
			// Check if the current dept's ID is in the target parent's ancestors.
			targetAncestorParts := strings.Split(targetParent.Ancestors, ",")
			ownIDStr := strconv.FormatUint(dept.ID, 10)
			for _, part := range targetAncestorParts {
				if part == ownIDStr {
					return apperror.BadRequest("不能将部门移动到其子部门下")
				}
			}
		}

		// Recalculate ancestors.
		if dept.ParentID == nil || *dept.ParentID == 0 {
			dept.Ancestors = strconv.FormatUint(dept.ID, 10)
		} else {
			parent, err := s.repo.FindByID(ctx, *dept.ParentID)
			if err != nil {
				if errors.Is(err, gorm.ErrRecordNotFound) {
					return apperror.BadRequest("父部门不存在")
				}
				return err
			}
			dept.Ancestors = parent.Ancestors + "," + strconv.FormatUint(dept.ID, 10)
		}
	}

	// When the parent changed, atomize Update + descendant recalculation.
	// Previously the descendant-recalc failure was only Warn'd: the API
	// returned success while the subtree pointed at a stale parent.
	if newParentID != oldParentID {
		if err := s.repo.UpdateWithAncestorsTx(ctx, dept); err != nil {
			s.logger.Warn("failed to update dept", zap.Uint64("deptId", req.ID), zap.Error(err))
			return err
		}
	} else if err := s.repo.Update(ctx, dept); err != nil {
		s.logger.Warn("failed to update dept", zap.Uint64("deptId", req.ID), zap.Error(err))
		return err
	}

	s.logger.Info("dept updated", zap.Uint64("deptId", req.ID))
	return nil
}

func (s *DeptService) Delete(ctx context.Context, id uint64) error {
	_, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return translateNotFound(err, "部门不存在")
	}

	hasChildren, err := s.repo.HasChildren(ctx, id)
	if err != nil {
		return err
	}
	if hasChildren {
		return apperror.BadRequest("请先删除子部门")
	}

	hasUsers, err := s.repo.HasUsers(ctx, id)
	if err != nil {
		return err
	}
	if hasUsers {
		return apperror.BadRequest("部门下存在用户，无法删除")
	}

	if err := s.repo.Delete(ctx, id); err != nil {
		s.logger.Warn("failed to delete dept", zap.Uint64("deptId", id), zap.Error(err))
		return err
	}
	s.logger.Info("dept deleted", zap.Uint64("deptId", id))
	return nil
}

// UpdateSort 批量应用排序值（「保存排序」，语义对齐菜单/角色管理）。
// 与 Update 的「精确落位(shift 兄弟)」语义不同，这里对每个条目直接覆盖赋值，
// 因为批量保存时用户在表格里已排好最终顺序，不应再触发逐条 shift 造成反复搬移。
func (s *DeptService) UpdateSort(ctx context.Context, req *request.UpdateDeptSortReq) error {
	for _, item := range req.Items {
		id := uint64(item.ID)
		if _, err := s.repo.FindByID(ctx, id); err != nil {
			return translateNotFound(err, "部门不存在")
		}
		if err := s.repo.UpdateSort(ctx, id, item.Sort); err != nil {
			s.logger.Warn("failed to update dept sort", zap.Uint64("deptId", id), zap.Error(err))
			return err
		}
	}
	s.logger.Info("dept sort updated", zap.Int("count", len(req.Items)))
	return nil
}

// buildDeptTree builds a tree structure from a flat list of departments.
func (s *DeptService) buildDeptTree(depts []entity.SysDept) []response.DeptResp {
	// 1. Convert entity to response.
	list := make([]response.DeptResp, 0, len(depts))
	for i := range depts {
		list = append(list, util.MapEntity[response.DeptResp](&depts[i], s.logger))
	}

	// 2. Group by parentID,并记录可见 ID 集合用于识别「局部根」。
	childrenMap := make(map[uint64][]response.DeptResp)
	idSet := make(map[uint64]bool, len(list))
	for _, item := range list {
		idSet[item.ID] = true
		childrenMap[item.ParentID] = append(childrenMap[item.ParentID], item)
	}

	// 3. Recursively build children.
	var build func(parentID uint64) []response.DeptResp
	build = func(parentID uint64) []response.DeptResp {
		children := childrenMap[parentID]
		if len(children) == 0 {
			return nil
		}
		result := make([]response.DeptResp, 0, len(children))
		for _, child := range children {
			child.Children = build(child.ID)
			if child.Children == nil {
				child.Children = []response.DeptResp{}
			}
			result = append(result, child)
		}
		return result
	}

	// 4. 顶层节点 = ParentID==0 的真正根,或父节点不在可见集合内(被数据范围
	// 裁剪)的节点。datascope 只会返回「某部门 + 其子孙」的子树、不含祖先链,
	// 若仍只从 build(0) 起建树,非根部门用户将得到空树。父节点被裁剪掉的节点
	// 作为该子树的局部根,让「本部门/本部门及以下/自定义/仅本人」等范围的用户
	// 也能看到自己的部门及其下级。
	roots := make([]response.DeptResp, 0)
	for _, item := range list {
		if item.ParentID == 0 || !idSet[item.ParentID] {
			child := item
			child.Children = build(child.ID)
			if child.Children == nil {
				child.Children = []response.DeptResp{}
			}
			roots = append(roots, child)
		}
	}

	// 顶层兜底：空树返回 [] 而非 nil，避免 Go 将 nil slice 序列化为 JSON null，
	// 导致前端消费方（如通知公告的部门下拉）对 null 调 .map 崩溃。
	if len(roots) == 0 {
		return []response.DeptResp{}
	}
	return roots
}
