package service

import (
	"context"

	"github.com/tangwy-t/webmanager-server/internal/model/dto/request"
	"github.com/tangwy-t/webmanager-server/internal/model/dto/response"
	"github.com/tangwy-t/webmanager-server/internal/model/entity"
	"github.com/tangwy-t/webmanager-server/internal/pkg/app"
	"github.com/tangwy-t/webmanager-server/internal/pkg/apperror"
	"github.com/tangwy-t/webmanager-server/internal/pkg/database"
	"github.com/tangwy-t/webmanager-server/internal/pkg/logger"
	"github.com/tangwy-t/webmanager-server/internal/pkg/util"

	"go.uber.org/zap"
)

// RoleRepositoryInterface 由 service/interface.go 迁移至此:接口定义在消费方,
// 不再维护包级中央接口文件。
// RoleRepositoryInterface defines the data-access contract for role management operations.
type RoleRepositoryInterface interface {
	FindPage(ctx context.Context, query *request.RoleQuery) ([]entity.SysRole, int64, error)
	FindAll(ctx context.Context) ([]entity.SysRole, error)
	FindByID(ctx context.Context, id uint64) (*entity.SysRole, error)
	CreateWithAssociations(ctx context.Context, role *entity.SysRole, menuIDs, deptIDs []uint64) error
	// UpdateWithAssociationsAndUserIDs atomically updates the role and its associations
	// within a single transaction, and returns the IDs of users assigned to this role
	// at the time the transaction runs — eliminating the race window between the
	// user-ID query and the DB update.
	UpdateWithAssociationsAndUserIDs(ctx context.Context, role *entity.SysRole, menuIDs, deptIDs []uint64) ([]uint64, error)
	Delete(ctx context.Context, id uint64) error
	DeleteWithAssociations(ctx context.Context, id uint64) error
	FindUserIDsByRoleID(ctx context.Context, roleID uint64) ([]uint64, error)
	UpdateStatus(ctx context.Context, id uint64, status int8) error
	UpdateSort(ctx context.Context, id uint64, sort int) error
}

type RoleService struct {
	repo         RoleRepositoryInterface
	logger       logger.LoggerInterface
	sessionStore SessionStoreInterface
}

// NewRoleService constructs a RoleService with the given dependencies.
// Snowflake ID generation is handled by GORM callbacks (database.RegisterIDCallback).
func NewRoleService(repo RoleRepositoryInterface, logger logger.LoggerInterface, sessionStore SessionStoreInterface) *RoleService {
	return &RoleService{repo: repo, logger: logger, sessionStore: sessionStore}
}

// toRoleResp 组装 RoleResp:基础字段映射 + 关联菜单/部门 ID 提取。
// FindPage/FindAll/FindByID 三处同形组装收敛于此(与 toUserResp 同模式)。
func toRoleResp(role *entity.SysRole, logger logger.LoggerInterface) response.RoleResp {
	r := util.MapEntity[response.RoleResp](role, logger)
	menuIDs := make([]uint64, 0, len(role.Menus))
	for _, m := range role.Menus {
		menuIDs = append(menuIDs, m.ID)
	}
	r.MenuIDs = util.JsonUint64Slice(menuIDs)
	deptIDs := make([]uint64, 0, len(role.Depts))
	for _, d := range role.Depts {
		deptIDs = append(deptIDs, d.ID)
	}
	r.DeptIDs = util.JsonUint64Slice(deptIDs)
	return r
}

func (s *RoleService) FindPage(ctx context.Context, query *request.RoleQuery) (*app.PageResponse, error) {
	roles, total, err := s.repo.FindPage(ctx, query)
	if err != nil {
		return nil, err
	}
	list := make([]response.RoleResp, 0, len(roles))
	for i := range roles {
		list = append(list, toRoleResp(&roles[i], s.logger))
	}
	return app.NewPageResponse(list, total, query.GetPage(), query.GetPageSize()), nil
}

func (s *RoleService) FindAll(ctx context.Context) ([]response.RoleResp, error) {
	roles, err := s.repo.FindAll(ctx)
	if err != nil {
		return nil, err
	}
	list := make([]response.RoleResp, 0, len(roles))
	for i := range roles {
		list = append(list, toRoleResp(&roles[i], s.logger))
	}
	return list, nil
}

func (s *RoleService) FindByID(ctx context.Context, id uint64) (*response.RoleResp, error) {
	role, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return nil, translateNotFound(err, "角色不存在")
	}
	resp := toRoleResp(role, s.logger)
	return &resp, nil
}

func (s *RoleService) Create(ctx context.Context, req *request.CreateRoleReq) (uint64, error) {
	// ID is auto-generated by the GORM BeforeCreate callback (database.RegisterIDCallback).
	role := &entity.SysRole{}
	util.CopyEntity(role, req, s.logger)
	if role.Status == nil {
		enabled := entity.RoleStatusEnabled
		role.Status = &enabled
	}

	if role.DataScope == nil {
		ds := int8(1)
		role.DataScope = &ds
	}

	menuIDs := []uint64(req.MenuIDs)
	if menuIDs == nil {
		menuIDs = []uint64{}
	}
	deptIDs := []uint64(req.DeptIDs)
	if deptIDs == nil {
		deptIDs = []uint64{}
	}

	if err := s.repo.CreateWithAssociations(ctx, role, menuIDs, deptIDs); err != nil {
		if database.IsDuplicateKey(err) {
			return 0, apperror.Conflict("角色代码已存在")
		}
		s.logger.Warn("failed to create role", zap.String("code", req.Code), zap.Error(err))
		return 0, err
	}
	s.logger.Info("role created", zap.Uint64("roleId", role.ID), zap.String("code", role.Code))
	return role.ID, nil
}

func (s *RoleService) Update(ctx context.Context, req *request.UpdateRoleReq) error {
	role, err := s.repo.FindByID(ctx, req.ID)
	if err != nil {
		return translateNotFound(err, "角色不存在")
	}

	util.CopyEntity(role, req, s.logger)

	menuIDs := []uint64(req.MenuIDs)
	if menuIDs == nil {
		menuIDs = []uint64{}
	}
	deptIDs := []uint64(req.DeptIDs)
	if deptIDs == nil {
		deptIDs = []uint64{}
	}

	// Atomically update the role and capture the affected user IDs in a single
	// transaction — eliminates the race between the user-ID query and the DB commit.
	userIDs, err := s.repo.UpdateWithAssociationsAndUserIDs(ctx, role, menuIDs, deptIDs)
	if err != nil {
		s.logger.Warn("failed to update role", zap.Uint64("roleId", req.ID), zap.Error(err))
		return err
	}

	// Invalidate permission cache for every user assigned to this role.
	// Failures are returned as errors rather than silently swallowed, so the
	// caller knows the cache may be stale and can retry.
	for _, uid := range userIDs {
		if err := s.sessionStore.RevokePerms(ctx, uid); err != nil {
			s.logger.Error("failed to revoke perms cache", zap.Uint64("userId", uid), zap.Error(err))
			return apperror.Internal("权限缓存刷新失败，请重试")
		}
	}
	s.logger.Info("role updated", zap.Uint64("roleId", req.ID))
	return nil
}

// UpdateStatus toggles a role's status from the list page's inline switch
// (0=停用 1=启用). The built-in admin role is not toggleable, mirroring
// the Delete guard. Invalidates the permission cache of every user assigned
// to this role so status changes take effect immediately.
func (s *RoleService) UpdateStatus(ctx context.Context, id uint64, status int8) error {
	role, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return translateNotFound(err, "角色不存在")
	}
	if role.Code == "admin" {
		return apperror.BadRequest("内置管理员角色不允许修改状态")
	}
	if err := s.repo.UpdateStatus(ctx, id, status); err != nil {
		s.logger.Warn("failed to update role status", zap.Uint64("roleId", id), zap.Error(err))
		return err
	}
	// 状态变更立即失效该角色下所有用户的权限缓存(停用后旧权限最长延迟
	// accessExpire 才失效)。
	userIDs, err := s.repo.FindUserIDsByRoleID(ctx, id)
	if err != nil {
		s.logger.Warn("failed to find users for role status change", zap.Uint64("roleId", id), zap.Error(err))
		return err
	}
	if s.sessionStore == nil {
		s.logger.Info("role status updated (no session store, perms cache untouched)",
			zap.Uint64("roleId", id), zap.Int8("status", status))
		return nil
	}
	for _, uid := range userIDs {
		if err := s.sessionStore.RevokePerms(ctx, uid); err != nil {
			s.logger.Error("failed to revoke perms cache", zap.Uint64("userId", uid), zap.Error(err))
			return apperror.Internal("权限缓存刷新失败，请重试")
		}
	}
	s.logger.Info("role status updated", zap.Uint64("roleId", id), zap.Int8("status", status))
	return nil
}

// UpdateSort 批量「保存排序」:与 Update 的关联替换语义不同,这里对每个条目
// 仅覆盖 sort 列,不触碰菜单/部门关联,也不影响权限缓存(排序纯展示)。
// 内置 admin 角色同样允许调整显示顺序。
func (s *RoleService) UpdateSort(ctx context.Context, req *request.UpdateRoleSortReq) error {
	for _, item := range req.Items {
		id := uint64(item.ID)
		if _, err := s.repo.FindByID(ctx, id); err != nil {
			return translateNotFound(err, "角色不存在")
		}
		if err := s.repo.UpdateSort(ctx, id, item.Sort); err != nil {
			s.logger.Warn("failed to update role sort", zap.Uint64("roleId", id), zap.Error(err))
			return err
		}
	}
	s.logger.Info("role sort updated", zap.Int("count", len(req.Items)))
	return nil
}

func (s *RoleService) Delete(ctx context.Context, id uint64) error {
	role, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return translateNotFound(err, "角色不存在")
	}

	// Cannot delete the admin role.
	if role.Code == "admin" {
		return apperror.BadRequest("不能删除管理员角色")
	}

	// Check if any users are assigned to this role before deletion.
	userIDs, err := s.repo.FindUserIDsByRoleID(ctx, id)
	if err != nil {
		s.logger.Warn("failed to find users for role deletion", zap.Uint64("roleId", id), zap.Error(err))
	}
	if len(userIDs) > 0 {
		return apperror.BadRequest("该角色下存在关联用户，无法删除")
	}

	s.logger.Info("role deleted", zap.Uint64("roleId", id))
	return s.repo.DeleteWithAssociations(ctx, id)
}
